### PR TITLE
new VSL functions

### PR DESCRIPTION
**Pull request by ehocdet**
. VSL_Name2Tag
. VSL_TAG
. VSL_DATA

### CODE REVIEW

**Comment by xcir** [comment]
Thank you for your PR. (And other PR, very thanks!)

- VSL_Name2Tag
I think VSL_tags_rev can be used.

- VSL_DATA
 Why last byte delete? ([8:-1])
 I think that should not be deleted if tag has a SLT_F_BINARY flag.

**Comment by ehocdet** [comment]
Thanks for the project!

- VSL_Name2Tag
Indeed, VSL_tags_rev do that. (I switch from 0.8)
Perhaps keep the same name as C API ?

- VSL_DATA
string_at with length  doesn't eat the '\0'. It could be  string_at(ptr, length + 8 -1)[8:]
you are right with binary DATA
Perhaps rename the func as VSL_StrDATA

**Comment by xcir** [comment]
- Perhaps keep the same name as C API ?
Original varnishapi does not have VSL_tags_rev.(VSL_tags_rev is what reversed the VSL_tags.)

- VSL_DATA
How about add isbinary option?

**Comment by ehocdet** [comment]
- it's VSL_Name2Tag:
https://github.com/varnishcache/varnish-cache/blob/master/include/vapi/vsl.h#L171

**Comment by xcir** [comment]
#Sorry in advance if my English is strange..

I think same interface is desirable if same name function.
VSL_Name2Tag is useful, But I don't know why add the VSL_Name2Tag only to VarnishAPI.
I think should add VSL_Name2Tag in LIBVARNISHAPI13 class.

**Comment by ehocdet** [comment]
- ok, i drop my  VSL_Name2Tag
(it disappear with commit ae12386d360f5f1fa8253d5477777a9d1ce24e2c)

- MR reworked with only VSL_TAG / VSL_DATA  and use case

**Comment by xcir** [comment]
merged thanks!

**Pull request merged**
